import {
  faBell,
  faGear,
  faLayerGroup,
  faPooStorm,
  faProjectDiagram,
  faSquarePlus,
  faUserPlus,
  faUsers,
  faWheelchairMove,
} from "@fortawesome/free-solid-svg-icons";
export const NavLinks = [
  {
    id: 1,
    name: "Users",
    to: "users",
    icon: faUsers,
    status: ["admin"],
    currentUrl: "/dashboard/users",
  },
  {
    id: 2,
    name: "AddUser",
    to: "users/add",
    icon: faUserPlus,
    status: ["admin"],
    currentUrl: "/dashboard/users/add",
  },
  {
    id: 3,
    name: "Categories",
    to: "categories",
    icon: faLayerGroup,
    status: ["writer", "admin"],
    currentUrl: "/dashboard/categories",
  },
  {
    id: 4,
    name: "AddCategory",
    to: "categories/add",
    icon: faSquarePlus,
    status: ["writer", "admin"],
    currentUrl: "/dashboard/categories/add",
  },
  {
    id: 5,
    name: "posts",
    to: "posts",
    icon: faPooStorm,
    status: ["writer", "admin"],
    currentUrl: "/dashboard/posts",
  },
  {
    id: 6,
    name: "AddPost",
    to: "posts/add",
    icon: faSquarePlus,
    status: ["writer", "admin"],
    currentUrl: "/dashboard/posts/add",
  },
  {
    id: 7,
    name: "Notifications",
    to: "notifications",
    icon: faBell,
    status: ["writer", "admin"],
    currentUrl: "/dashboard/notifications",
  },
  {
    id: 8,
    name: "Settings",
    to: "settings",
    icon: faGear,
    status: ["admin"],
    currentUrl: "/dashboard/settings",
  },
];
